- datasophon-common/pom.xml
- datasophon-common/src/main/java/com/datasophon/common/utils/HostUtils.java
- datasophon-common/src/main/test/com/datasophon/common/test/HostUtilsTest.java
optimize and add test class for class HostUtils
> [issues#5][Service]optimize and add test class for class HostUtils

- README.md
- README_EN.md
Translate the README.md file to english.
> issue#41 [Feature Request]: README.md translate to english

- datasophon-api/src/main/java/com/datasophon/api/master/ActorUtils.java
> [Enhancement]: Eliminate several issues of com.datasophon.api.master.ActorUtils 

- datasophon-api/src/main/java/com/datasophon/api/utils/CommonUtils.java
update CommonUtils.convertRoleType function.
> chore: update CommonUtils.convertRoleType function.

- README.md
- README_CN.md
Change the URL of Office Website.
> Office Website URL changed.

- datasophon-api/src/main/java/com/datasophon/api/master/HdfsECActor.java
- datasophon-api/src/main/java/com/datasophon/api/master/service/StarRocksActor.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/ClusterServiceRoleInstanceServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/utils/CheckUtils.java
- datasophon-api/src/main/java/com/datasophon/api/utils/CommonUtils.java
- datasophon-api/src/main/java/com/datasophon/api/utils/HadoopUtils.java
- datasophon-api/src/main/java/com/datasophon/api/utils/HostsValidator.java
- datasophon-api/src/main/java/com/datasophon/api/utils/HttpUtils.java
- datasophon-api/src/main/java/com/datasophon/api/utils/MinaUtils.java
- datasophon-api/src/main/java/com/datasophon/api/utils/PackageUtils.java
- datasophon-api/src/main/java/com/datasophon/api/utils/ProcessUtils.java
- datasophon-api/src/main/java/com/datasophon/api/utils/SshTools.java
- datasophon-api/src/main/java/com/datasophon/api/utils/StarRocksUtils.java
- datasophon-common/src/main/java/com/datasophon/common/Constants.java
datasophon-api工程下的utils目录中工具类相关编码规范修改以及优化
> datasophon-api工程下的utils目录工具类相关编码规范修改

- datasophon-common/src/main/java/com/datasophon/common/Constants.java
- datasophon-worker/src/main/java/com/datasophon/worker/WorkerApplicationServer.java
- datasophon-worker/src/main/java/com/datasophon/worker/actor/LogActor.java
- datasophon-worker/src/main/java/com/datasophon/worker/handler/InstallServiceHandler.java
- datasophon-worker/src/main/java/com/datasophon/worker/handler/ServiceHandler.java
- datasophon-worker/src/main/java/com/datasophon/worker/strategy/ServiceRoleStrategyContext.java
- datasophon-worker/src/main/java/com/datasophon/worker/utils/FreemakerUtils.java
> Modify coding specification 

- datasophon-api/src/main/resources/sql/datasophon-1.0.1.sql
The t_ddh_cluster_service_dashboard table adds dashboards for ds and streampark
> The t_ddh_cluster_service_dashboard table adds dashboards for ds and streampark

- datasophon-api/src/main/java/com/datasophon/api/master/DispatcherWorkerActor.java
- datasophon-api/src/main/java/com/datasophon/api/utils/MinaUtils.java
when restartWorkerDispatcher sshd connect Auth failed , because the id_rsa file content not be read
> fix: restartWorkerDispatcher sshd connect Auth failed 

- datasophon-api/src/main/java/com/datasophon/api/enums/Status.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/ServiceInstallServiceImpl.java
[Feature] Check whether service AlertManager, Grafana and Prometheus on the same node.
> [Feature] Check whether service on the same node.

- datasophon-ui/src/components/steps/step7.vue
- datasophon-ui/src/components/tool/AStepItem.vue
- datasophon-ui/src/pages/serviceManage/setting.vue
Variable declaration definition changed (var to let)
> Variable declaration definition changed (var to let)

- datasophon-api/src/main/java/com/datasophon/api/master/DAGBuildActor.java
- datasophon-api/src/main/java/com/datasophon/api/master/ServiceCommandActor.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/ClusterServiceCommandHostCommandServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/ClusterServiceCommandHostServiceImpl.java
- datasophon-common/src/main/java/com/datasophon/common/Constants.java
Remove constant Constants.COMMAND_ID, and use SFunction instead.
> perf: Remove constant Constants.COMMAND_ID, and use SFunction instead.

- datasophon-ui/src/components/steps/step7.vue
Variable declaration definition changed (var to let) #169
Introduce one more letter to bring new problems, remove letters Y
> datasophon step7.vue remove the extra letter y

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/document.yml
- .github/ISSUE_TEMPLATE/improvement-report.yml
- .github/PULL_REQUEST_TEMPLATE.md
> [Feature] [.git] Added issue template

- .pre-commit-config.yaml
- pom.xml
- style/license_header
Added spotless
- Added spotless
> [Feature] [.] Added spotless

- datasophon-api/src/main/java/com/datasophon/api/load/LoadServiceMeta.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/InstallServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/strategy/GrafanaHandlerStrategy.java
- datasophon-api/src/main/java/com/datasophon/api/strategy/ZkServerHandlerStrategy.java
- datasophon-api/src/main/java/com/datasophon/api/utils/ProcessUtils.java
- datasophon-common/src/main/java/com/datasophon/common/Constants.java
- datasophon-common/src/main/java/com/datasophon/common/utils/HostUtils.java
1.delete read hosts file code and host_ip/ip_host cache
2.add utils get ip and hostname use InetAddress
3.delete  unused code related this functions
> [Feature-185][common] optimize read hosts file

- datasophon-common/pom.xml
> fix(datasophon-common): 升级jsch版本

- datasophon-api/pom.xml
- datasophon-api/src/main/java/com/datasophon/api/configuration/AppConfiguration.java
- datasophon-api/src/main/java/com/datasophon/api/configuration/SwaggerConfiguration.java
- datasophon-api/src/main/java/com/datasophon/api/controller/SystemSettingController.java
- datasophon-api/src/main/java/com/datasophon/api/service/SystemSettingService.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/SystemSettingServiceImpl.java
> Add Swagger

- datasophon-api/src/main/java/com/datasophon/api/controller/AlertGroupController.java
- datasophon-api/src/main/java/com/datasophon/api/controller/UserInfoController.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/AlertGroupServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/ClusterAlertHistoryServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/ClusterAlertQuotaServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/ClusterHostServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/ClusterServiceRoleInstanceServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/FrameServiceServiceImpl.java
- datasophon-common/src/main/java/com/datasophon/common/Constants.java
- datasophon-common/src/main/java/com/datasophon/common/utils/Result.java
Remove some constant in class Constants, and use SFunction instead.
Remove constant Constants.ID/ALERT_GROUP_ID/ALERT_QUOTA_NAME/ALERT_GROUP_NAME/ALERT_LEVEL, and use SFunction instead.
> [Perf] Remove some constant in class Constants, and use SFunction instead.

- .gitignore
- datasophon-api/src/main/java/com/datasophon/api/configuration/AppConfiguration.java
- datasophon-api/src/main/java/com/datasophon/api/controller/AlertGroupController.java
- datasophon-api/src/main/java/com/datasophon/api/controller/UserInfoController.java
- datasophon-api/src/main/java/com/datasophon/api/interceptor/UserPermissionHandler.java
- datasophon-api/src/main/java/com/datasophon/api/master/DispatcherWorkerActor.java
- datasophon-api/src/main/java/com/datasophon/api/master/HostActor.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/AlertGroupServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/ClusterAlertHistoryServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/ClusterAlertQuotaServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/ClusterHostServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/ClusterServiceRoleInstanceServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/FrameServiceServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/InstallServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/utils/MinaUtils.java
- datasophon-api/src/main/resources/application.yml
- datasophon-common/src/main/java/com/datasophon/common/Constants.java
- datasophon-common/src/main/java/com/datasophon/common/utils/Result.java
- datasophon-ui/.env
- datasophon-ui/deploy.config.js
- datasophon-ui/deploy.sh.js
- datasophon-ui/package.json
- datasophon-ui/pom.xml
- datasophon-ui/src/pages/serviceManage/setting.vue
- datasophon-ui/src/router/index.js
- datasophon-ui/vue.config.js
> [Feature] Unified Front and back end

- datasophon-api/src/main/java/com/datasophon/api/master/PrometheusActor.java
已安装starrocks
1.修改Prometheus的配置文件
/opt/datasophon/prometheus-2.17.2/configs/starrocks.json 中targets属性
2.curl -X POST -d "" http://ip:9090/-/reload ip指的是Prometheus的Host地址
修复Starrocks 监控问题
*(or)*
(or)
(or)
> fix(datasophon-api): 修复监控将fe配置成了be的问题以及格式化代码

- datasophon-api/src/main/resources/datasophon-api.sh
1. 调整JVM参数适应高版本 JDK，移除内存优化参数，部分JDK不适用；
2. 移除 DOLPHINSCHEDULER_LOG_DIR copy 内容；
3. 对获取 DDH HOME 提供更准确的脚本；
经过测试，兼容修改前的脚本，无其他不兼容影响。
调整后，对使用 DDH_HOME 使用绝对路径，而不是之前的相对 bin .. 的路径：
```shell
ps -ef |grep DDH
root      3319     1 99 01:28 pts/0    00:00:15 /usr/local/jdk1.8.0_333/bin/java -Dlogging.config=classpath:logback-api.xml -Dspring.profiles.active=api -Xms1g -Xmx1g -Xmn512m -server -javaagent:/opt/datasophon/datasophon-manager-1.1.0/jmx/jmx_prometheus_javaagent-0.16.1.jar=8586:/opt/datasophon/datasophon-manager-1.1.0/jmx/jmx_exporter_config.yaml -classpath /opt/datasophon/datasophon-manager-1.1.0/conf:/opt/datasophon/datasophon-manager-1.1.0/lib/* com.datasophon.api.DDHApplicationServer
```
> 调整JVM参数适应高版本 JDK，移除内存优化参数，部分JDK不适用，移除 DOLPHINSCHEDULER_LOG_DIR copy

- datasophon-api/src/main/resources/meta/DDP-1.0.0/DINKY/service_ddl.json
- datasophon-api/src/main/resources/meta/DDP-1.0.0/DS/service_ddl.json
- datasophon-api/src/main/resources/sql/datasophon.sql
- datasophon-worker/src/main/resources/templates/dinky.ftl
Upgrade Dinky to v0.7.2, DolphinScheduler to v3.1.4.
*(or)*
(or)
(or)
> [Improvement-214][Service packages] Upgrade Dinky to v0.7.2, DolphinScheduler to v3.1.4

- datasophon-api/pom.xml
- datasophon-api/src/main/resources/assembly.xml
- datasophon-api/src/main/resources/datasophon-api.sh
- datasophon-ui/pom.xml
- datasophon-worker/pom.xml
- datasophon-worker/src/main/resources/assembly.xml
- pom.xml
调整 UI 打包和本工程依赖
1. 调整 UI 打包，使无需 copy dist 到 api resource，而 api 在 package assembly  时一起打包 UI dist；
2. 使工程内部的依赖依赖项目的版本，而不是指定的版本；
3. 增加 versions-maven-plugin，使升级版本更加规范；
> 调整 ui 和 api 的打包结构，增加versions-maven-plugin

- datasophon-api/src/main/java/com/datasophon/api/master/WorkerStartActor.java
- datasophon-api/src/main/java/com/datasophon/api/service/ClusterServiceCommandService.java
- datasophon-api/src/main/java/com/datasophon/api/service/ClusterServiceRoleInstanceService.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/ClusterServiceCommandServiceImpl.java
- datasophon-api/src/main/java/com/datasophon/api/service/impl/ClusterServiceRoleInstanceServiceImpl.java
Auto-start services when worker restart.
1. Add autoStartServiceNeeded() method in class WorkerStartActor.
2. Add batch generate command method generateServiceRoleCommand in class ClusterServiceCommandServiceImpl.
3. Add query stopped service method at class ClusterServiceRoleInstanceServiceImpl.
> [#218][feat] Auto-start services when worker restart.

- datasophon-api/src/main/java/com/datasophon/api/master/ActorUtils.java
- datasophon-api/src/main/java/com/datasophon/api/master/MasterNodeProcessingActor.java
- datasophon-api/src/main/java/com/datasophon/api/master/handler/service/ServiceStartHandler.java
- datasophon-common/src/main/java/com/datasophon/common/command/OlapOpsType.java
- datasophon-common/src/main/java/com/datasophon/common/command/OlapSqlExecCommand.java
- datasophon-common/src/main/java/com/datasophon/common/command/ServiceRoleOperateCommand.java
- datasophon-common/src/main/java/com/datasophon/common/utils/OlapUtils.java
- datasophon-worker/src/main/java/com/datasophon/worker/WorkerApplicationServer.java
- datasophon-worker/src/main/java/com/datasophon/worker/strategy/BEHandlerStrategy.java
- datasophon-worker/src/main/java/com/datasophon/worker/strategy/FEHandlerStrategy.java
- datasophon-worker/src/main/java/com/datasophon/worker/utils/ActorUtils.java
> fix the bug of adding starrocks backend and follower.

- .github/workflows/codeql.yml
- .github/workflows/issue-robot.yml
- .gitmodules
1. codeql for code security
2. translate issue boy and tite to english.
> add github robot for auto workflow

- .github/workflows/maven.yaml
> [fix] Skip the build of ui and api add the build command in pull_request

- datasophon-common/src/main/java/com/datasophon/common/Constants.java
- datasophon-common/src/main/resources/common.properties
- Customize ID_RSA value in common.properties
> Custom ID_RSA feature in Constants.java and config file
